import sqlite3

def main() -> None:
    conn = sqlite3.connect('solus_bingo.db')
    cursor = conn.cursor()

    cursor.execute('SELECT rsn FROM players where lower(build) like "%zerker%"')
    existing_players = cursor.fetchall()
    roster = [
        'NARUT0',
        'St0rmfire1ce',
        'GimReign',
        'Muxzy',
        'DrummStyx',
        'Sierzy',
        'Nfamy',
        'Solodinsky',
        'williee FE',
        'Shriel GIM',
        'Reid Topaz',
        'Miko Iino',
        'Mitbot',
        'E4ego',
        'HCIM Jorrd',
        'Vilsif',
        'boss boobies',
        'buff boobies',
        'blue boobies',
        'bruh boobies',
        'butt boobies',
        'Soft Erin',
        'Karlsonsk',
        'Get Quenched',
        'Lutakk0',
        'BigFackenLez',
        'J Air Wolf',
        'Iron McSalty',
        'ItsCommitted',
        'D Z N',
        'GIM dweeb',
        'KimKsFakeAss',
        'Pocky Styx',
        'puzi',
        'gilfboy',
        'jobirdup',
        'GIMPbsw',
        'LiaAzura',
        'Chernoburn',
        'Sharp Gnome',
        'BartenderBTW',
        'C ubano',
        'Runeferyearz',
        'biggie benz',
        'Buzzbonez',
        'T Coot',
        'oven nuggies',
        'K evboi',
        '1poop',
        'Roo K',
        'Poop Styx',
        'FeDuckers',
        'Sad Fat Ugly',
        'Nourd',
        'Planet Booty',
        'J1minem',
        'gif this',
        'I Am Mav',
        'Silly Ken',
        'Mistik Lucre',
        'Im Jumanji',
        'Ponylover 22',
        'Tick Fart',
        'Shrimpuuu',
        'Shrek BTW',
        'Lucky Lei',
        'Top Chook',
        'DDM',
        'Boo oobies',
        'GIMThunder',
        'IMissTrading',
        'Petpet',
        '5304',
        'LS Enjoyer',
        'Dymes',
        'sick chimp',
        'xo beav',
        'Primal sin',
        'Zredd FE',
        'Mega Sableye',
        'Kwemmy',
        'Watasha',
        'Jar of Cream',
        'japan ping',
        'AppleCobbler',
        'Astoric',
        'DedVenomed',
        'BlG Woody',
        'DiedAtWinter',
        'LurkinLuna',
        'Testament',
        'Raukey',
        'Half Jewish',
        'gimdonny',
        'Craw',
        'Iron Bending',
        'Boom3r br0',
        'Jelly',
        'At Tob',
        'd morgan93',
        'bnson',
        'Easy solo',
        'Cambrid',
        'Shaymins',
        'Winsbaby',
        'Decadise',
        'Oblv Frank',
        'sys REconfig',
        'Femboy Fluke',
        'Depict',
        'razzle',
        'iNoah Guy',
        'Fe FuryDR',
        'YamzTheKid',
        'serp bro',
        'Ty4k',
        'Insectkoala',
        'uncle juffy',
        'learningosrs',
        'Hendricks0n',
        'lostNewfie',
        'fcms',
        'dogshirt',
        'Ferrous Dice',
        'big fricker',
        'PristineCoom',
        'Raggie GIM',
        'Boomerclicks',
        'SomethingBTW',
        'Borgors',
        'Mrs Bnv',
        'Bnv VII',
        'IronFret',
        'UIM g o o',
        'Shifty Bits',
        'I meme hard',
        'Mr Burrito',
        'GIM Mylly',
        'Escad',
        'KiliPleb',
        'Andy Burt',
        'Dad I',
        'M1ke Jones',
        'i r bert',
        'Tex Two',
        'AFK is EZ',
        'Ureky',
        'Snoop rs',
        'also falldyl',
        'Vallk',
        'sorryskiller',
        'SteveCd',
        'turtlefan124',
        'Whiskey Shot',
        'BlG FROSTY',
        'I am A a ron',
        'Lups XD',
        'Snaccs',
        'Towm8r',
        'Risout',
        'I Proud End',
        'Skrrrtle',
        'Azhyiron',
        'IronHyperion',
        'probgunnadie',
        'Iron irony',
        'Giggle Gamer',
        'GrassFedTofu',
        'Lohruken',
        'GIMPAPPLEWEJ',
        'Femboy bike',
        'A Lovely Leo',
        'molten ass',
        'AMILIFE',
        'Anida Dump',
        'Hot Tie Guy',
        'Zerus259',
        'Melon Queen',
        'BUZZERTON',
        'T ylor',
        'Bear toe',
        'Darth Scy',
        'Sceffen',
        'BlG MOBY',
        'Yoju',
        'S amuraii',
        'joey skrrrt',
        'Thibokes',
        'Grog the Orc',
        'AAAAAddy',
        'Marie Fey',
        'Earth Melon',
        'Femboy Rio',
        'McDoubles',
        'Praise B',
        'Beerpoops',
        'Obesity',
        'oopsimiron',
        'BuchuLover73',
        'PoleVault'
    ]
    zerkers = []
    existing_players = [row[0] for row in existing_players]
    for rsn in existing_players:
        print(rsn)
        if rsn in roster:
            zerkers.append(rsn)

    print(zerkers)

if __name__ == '__main__':
    main()
